services:
  mockapi:
    restart: unless-stopped
    container_name: app_mockapi
    ports:
      - 0.0.0.0:${PORT}:${PORT}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}

  node_exporter: # machine metrics to be scraped by prometheus
    image: prom/node-exporter:v1.8.2
    container_name: app_node_exporter
    restart: unless-stopped
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"
    ports:
      - 0.0.0.0:9100:9100

  caadvisor: # container metrics to be scraped by prometheus
    image: gcr.io/cadvisor/cadvisor:v0.50.0
    container_name: app_caadvisor
    restart: unless-stopped
    volumes:
      - "/dev/disk/:/dev/disk:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/sys:/sys:ro"
      - "/var/run:/var/run:ro"
      - "/:/rootfs:ro"
    ports:
      - 0.0.0.0:8080:8080

  promtail: # machine and container logs ships to grafana
    image: grafana/promtail:3.1.1
    container_name: app_promtail
    restart: unless-stopped
    volumes:
      - /var/log:/var/log:ro
      - /etc/hostname:/etc/hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app-promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
