global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "ghost_node_exporter"
    static_configs:
      - targets: ["18.130.208.95:9100"]

  - job_name: "ghost_cadvisor"
    static_configs:
      - targets: ["18.130.208.95:8080"]
