global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "observability_node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "observability_caadvisor"
    static_configs:
      - targets: ["caadvisor:8080"]

  - job_name: "mockapi_node_exporter"
    static_configs:
      - targets: ["18.171.205.203:9100"]

  - job_name: "mockapi_caadvisor"
    static_configs:
      - targets: ["18.171.205.203:8080"]

  - job_name: "observability_jaeger"
    static_configs:
      - targets: ["jaeger:16686"]
